import { motion } from 'framer-motion';

const categoryColors = {
  Subject: 'from-cyan-500 to-blue-500',
  'Current Events': 'from-purple-500 to-pink-500',
  History: 'from-amber-500 to-orange-500',
  Sports: 'from-green-500 to-emerald-500',
  Mixed: 'from-violet-500 to-indigo-500'
};

const missionCatalog = [
  {
    id: 'general-study',
    topic: 'general study including english, mathematics, science, and social science concepts for quiz practice',
    title: 'General Study',
    description: 'English, math, science, and social science mixed into one core study mission.',
    category: 'Subject',
    difficulty: 'medium',
    questionCount: 10
  },
  {
    id: 'current-events',
    topic: 'current affairs and important events happening around the world right now including politics, economy, science, and society',
    title: 'Current Affairs',
    description: 'World current events regenerated by AI every time the player starts a new quiz.',
    category: 'Current Events',
    difficulty: 'medium',
    questionCount: 10
  },
  {
    id: 'sports',
    topic: 'sports quiz covering cricket, football, olympics, athletes, tournaments, records, and sporting moments',
    title: 'Sports',
    description: 'A sports-only AI mission that generates a different playable set each time.',
    category: 'Sports',
    difficulty: 'medium',
    questionCount: 10
  },
  {
    id: 'mixed-quiz',
    topic: 'a mixed quiz combining general study, current affairs, and sports into one diverse challenge',
    title: 'Mixed Quiz',
    description: 'A combined challenge across study topics, current affairs, and sports in one AI quiz.',
    category: 'Mixed',
    difficulty: 'medium',
    questionCount: 10
  }
];

export default function QuizList({ onSelectQuiz, generatingMissionId }) {
  return (
    <div>
      <div className="mb-6">
        <div>
          <p className="text-sm uppercase tracking-[0.24em] text-cyan-300">Mission Select</p>
          <h2 className="mt-2 text-4xl font-black text-white">Pick Your Next Quiz</h2>
        </div>
      </div>
      <div className="grid grid-cols-1 gap-5 md:grid-cols-2">
        {missionCatalog.map((quiz, idx) => (
          <motion.div
            key={quiz.id}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: idx * 0.1 }}
            onClick={() => onSelectQuiz(quiz)}
            className={`quiz-tile relative cursor-pointer overflow-hidden rounded-[28px] p-6 transition-transform hover:-translate-y-1 ${categoryColors[quiz.category]}`}
          >
            <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(255,255,255,0.18),transparent_28%)]"></div>
            <div className="relative">
              <div className="mb-6 flex items-start justify-between gap-4">
                <div>
                  <p className="text-xs uppercase tracking-[0.22em] text-cyan-100/80">AI Mission</p>
                  <h3 className="mt-3 text-2xl font-black text-white">{quiz.title}</h3>
                </div>
                <div className="rounded-full border border-white/20 bg-white/10 px-3 py-1 text-xs font-semibold uppercase tracking-[0.2em] text-white/80">{quiz.category}</div>
              </div>
              <p className="min-h-12 text-sm leading-6 text-slate-100/85">{quiz.description}</p>
              <div className="mt-5 flex items-center justify-between text-sm">
                <span className="text-white/70">{quiz.questionCount} questions</span>
                <span className="font-semibold text-cyan-100">{generatingMissionId === quiz.id ? 'Generating...' : 'Play now'}</span>
              </div>
            </div>
          </motion.div>
        ))}
      </div>
    </div>
  );
}
